import type { Metadata } from "next";
import "./globals.css";
import MainMenu from "@/components/layout/MainMenu";
import { Box } from "@mui/material";
import { Providers } from "./Providers";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box sx={{ display: "flex", flexDirection: "row" }}>
            <MainMenu />
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                bgcolor: "",
                width: "100%",
              }}
            >
              <Header />
              {children}
              <Footer />
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
