import type { Metadata } from "next";
import "./globals.css";
import MainMenu from "@/components/layout/MainMenu";
import { Styledroot } from "./Styledroot";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ display: "flex", flexDirection: "row" }}>
          <MainMenu />
          <Styledroot> {children}</Styledroot>
        </Box>
      </body>
    </html>
  );
}
